### ISSUE TITLE
When will the training code be released?

### ISSUE THREAD

**Issue by zhangquan97** [yhZhai/WSCL#1]
When will the training code be released?

**Comment by yhZhai** [comment]
We will release the code around late November. Thank you for your attention!

**Comment by zhangquan97** [comment]
> We will release the code around late November. Thank you for your attention!

Thank you for your reply! Looking forward to the release of the training code!

**Comment by yhZhai** [comment]
Hi there, thank you for your interest! We have just released the code.

**Comment by zhangquan97** [comment]
thank you.
