### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by qiyuebobo** [yhZhai/WSCL#10]
dear author:
   may I ask u how to switch the .dhf5 to .tif?
thanks!

**Comment by yhZhai** [comment]
Hi there,

Thank you for your interest in our paper! I am not sure about your question.

If you are trying to convert the .hdf5 file to .tif or .png files, you can iterative the dataset, and save the each image at [this line](https://github.com/yhZhai/WSCL/blob/7ea326bc38a226454cd738a0f3b1d8909b3bfa78/datasets/dataset.py#L92) 

If you are trying to replace the .hdf5 dataset with your custom .tif or .png datasets, you can follow the instructions [here](https://github.com/yhZhai/WSCL?tab=readme-ov-file#2-data-preparation). If our dataset does not detect a .hdf5 file, it will automatically iterative through all paths in the datalist file.

Please let me know any other questions. Thanks!

**Comment by qiyuebobo** [comment]
thank u for your rapid feedback! I'd like to confirm again: if I download the HDF5 dataset you provided and place it in the "data" folder, will the system automatically detect and test it? Additionally, if I have my own dataset in PNG format, can I specify the exact path for each image according to the JSON file format? So, in summary, I can choose to use either the HDF5 dataset or combine JSON format with my own dataset, is that correct?

**Comment by yhZhai** [comment]
Thank you for the clarification! Our dataset can automatically detect if a .hdf5 file is presented or not, and will use it if it exists, due to faster speed.
Using your own dataset in .png format is totally fine, as long as the path in the datalist file is correct.
