### ISSUE TITLE
My replication results differ from those in the paper. Is this within a reasonable range?

### ISSUE THREAD

**Issue by qiyuebobo** [yhZhai/WSCL#11]
Dear author, I obtained results using your code, and there are significant differences in the red-boxed area. Please advise. Thank you so much~!
![image](https://github.com/yhZhai/WSCL/assets/76613430/428e82d2-4288-4660-a6ba-e5eba8a21b01)

**Comment by yhZhai** [comment]
Hi there,

Thank you for trying out our code and for your feedback!

We've observed similar issues in our experiments, where threshold-dependent results can vary significantly. The F1 scores represent a trade-off between sensitivity and specificity. In your case, achieving higher sensitivity but lower specificity has impacted the overall F1 score.

For more consistent evaluation, we recommend using threshold-agnostic metrics like AUC, which tends to be more stable across different settings and environments. This should provide a more reliable measure of the model's performance.

**Comment by qiyuebobo** [comment]
Dear author,

Thank you for sharing such constructive findings with me! As you mentioned, in the last line of the performance summary, we can observe that the image AUC achieved in my training is 0.57, slightly lower than yours (by 1%), yet notably more stable.

Thanks again!
