### ISSUE TITLE
Regarding the issue of paper evaluation data

### ISSUE THREAD

**Issue by CongYep** [yhZhai/WSCL#5]
![image](https://github.com/yhZhai/WSCL/assets/49831693/19211b94-1188-4c66-ace9-e7c5f90e9202)

Is the Pixel-Level F1 in Table 4 trained on the casia v2 dataset? 
Do the six test sets only contain tampered images and no real images?
How is the combined F1 score calculated?

![image](https://github.com/yhZhai/WSCL/assets/49831693/84ff5eb6-853d-4397-a57c-c2e0d338c841)
Is the image-Level F1 in Table 2 trained on the casia v2 dataset? test on both real and tempered images?

**Comment by yhZhai** [comment]
Hi there, thank you for your interest in our paper, below we answer your questions.

1. Is the Pixel-Level F1 in Table 4 trained on the casia v2 dataset?
Yes, we only train the model on the CASIA v2 dataset, and evaluate the same model on five different datasets. Please refer to Table 1 for the details.

2. Do the six test sets only contain tampered images and no real images?
Yes, for evaluating the pixel-level performances, we only leverage tampered images.

3. How is the combined F1 score calculated?
The combined F1 is the harmonic mean of the pixel-level F1 and the image-level F1 from each dataset. Please refer to the Implementation Details paragraph for the details.

4. Is the image-Level F1 in Table 2 trained on the casia v2 dataset? test on both real and tempered images?
Yes, similar to the question 1, the model is also trained only on CASIA v2 (Table 1), and tested on both pristine and tampered images.

Please let me know if any further problems. Thanks!
