### ISSUE TITLE
About pretrained weights

### ISSUE THREAD

**Issue by chenhanch** [yhZhai/WSCL#6]
Could you please provide a pretrained model？Thank you very much

**Comment by yhZhai** [comment]
Hi there, thanks for your interest!

We will release the pretrained checkpoint soon. Additionally, we have successfully used this repository to reproduce the results mentioned in our paper. The performance aligns with what we've reported, so we encourage you to give it a try.

Thank you for your support!

**Comment by yhZhai** [comment]
Hi there, we have just released our pre-trained checkpoint at https://buffalo.app.box.com/folder/238544356629.
