### ISSUE TITLE
Pseudo-label voting mechanism

### ISSUE THREAD

**Issue by Stitchsong** [yhZhai/WSCL#7]
Dear author, I am deeply grateful for your work and for making it open source. I have a question regarding your code: could you please indicate where in the code you have implemented the pseudo-label voting mechanism? Thank you very much！

**Comment by yhZhai** [comment]
Hi there, thank you for your interest in our work! We implement the voting mechanism [here](https://github.com/yhZhai/WSCL/blob/2800337df1c462e0f171933e6f40a0fbfa0509db/models/ensemble_model.py#L25), and the loss is implemented [here](https://github.com/yhZhai/WSCL/blob/2800337df1c462e0f171933e6f40a0fbfa0509db/losses/multi_view_consistency_loss.py#L22). Please let me know if you have any other question.

**Comment by Stitchsong** [comment]
thank you so much！
