### ISSUE TITLE
About DETR

### ISSUE THREAD

**Issue by Stitchsong** [yhZhai/WSCL#8]
Dear author, sry to bother you. 
I want to ask do you use DETR？I didn't find the code about the DETR, but you thank the DETR in the Acknowledgement.

**Comment by yhZhai** [comment]
Thank you for your attention to detail in our project. We indeed drew inspiration from the DETR codebase, particularly focusing on its training and inference pipeline as well as the logging components.

**Comment by Stitchsong** [comment]
Thank you for your patient responses. I also wanted to inquire about the possibility of making the IMD2020 datalist.json and hdf5 files publicly available
