### ISSUE TITLE
About test demo

### ISSUE THREAD

**Issue by Samarium-Z** [yhZhai/WSCL#9]
Deeply thankful to your work!
I want to test the model on my own dataset, could you please provide a test demo?
Thank you so much!

**Comment by yhZhai** [comment]
Hi there,
Thank you for asking! For the current version, you can build a datalist JSON file and modify the evaluation YAML file for testing on your own dataset, as described [here](https://github.com/yhZhai/WSCL#2-data-preparation).

I would provide a test demo in one or two weeks.

**Comment by Samarium-Z** [comment]
> Hi there, Thank you for asking! For the current version, you can build a datalist JSON file and modify the evaluation YAML file for testing on your own dataset, as described [here](https://github.com/yhZhai/WSCL#2-data-preparation).
> 
> I would provide a test demo in one or two weeks.

Thanks for your reply! Looking forward to the release of the test demo!

**Comment by yhZhai** [comment]
Hi there,

I have added a `demo.py` for local demo purpose, check [here](https://github.com/yhZhai/WSCL?tab=readme-ov-file#4-demo) for the usage.

Besides, I have also prepared a Gradio demo at [here](https://huggingface.co/spaces/yhzhai/WSCL), please also have a try :)

Thank you for your interest!

**Comment by Samarium-Z** [comment]
> Hi there,
> 
> I have added a `demo.py` for local demo purpose, check [here](https://github.com/yhZhai/WSCL?tab=readme-ov-file#4-demo) for the usage.
> 
> Besides, I have also prepared a Gradio demo at [here](https://huggingface.co/spaces/yhzhai/WSCL), please also have a try :)
> 
> Thank you for your interest!

That's very nice! It helps me a lot. Thank u so*n much!
